blueprint:
  name: Desligar Lâmpadas em Horário Fixo
  description: Desliga automaticamente várias lâmpadas todos os dias em um horário fixo, se estiverem ligadas.
  domain: automation
  input:
    target_lights:
      name: Lâmpadas
      description: Lâmpadas a serem verificadas e desligadas se estiverem ligadas.
      selector:
        target:
          entity:
            domain: light
    scheduled_time:
      name: Horário
      description: Horário diário para verificar e desligar as lâmpadas ligadas.
      default: "22:00:00"
      selector:
        time:

trigger:
  - platform: time
    at: !input scheduled_time

action:
  - repeat:
      for_each: >
        {{ expand(inputs.target_lights) | map(attribute='entity_id') | list }}
      sequence:
        - condition: template
          value_template: "{{ is_state(repeat.item, 'on') }}"
        - service: light.turn_off
          data:
            entity_id: "{{ repeat.item }}"

mode: single
